In [1]:
import torch

# 1 Create Tensor

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x = torch.empty(5, 3) # creates a tensor without initializing its elements
x

tensor([[ 3.2454e-35,  0.0000e+00, -1.6678e-03],
        [ 4.5761e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
x = torch.rand(5, 3) # create a randomly initialized tensor
x

tensor([[0.2410, 0.9399, 0.2702],
        [0.0530, 0.3575, 0.6783],
        [0.9059, 0.5393, 0.9371],
        [0.5031, 0.4585, 0.1424],
        [0.4205, 0.7416, 0.5608]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

#### Attribute:

In [7]:
x = torch.arange(12)
x.shape

torch.Size([12])

In [8]:
x.size()

torch.Size([12])

torch.Size is a tuple

In [9]:
x.numel()

12

#### reshape a tensor but do not change the numel and values

In [10]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

#### all 0, all 1, other constants or sample each element randomly (and independently) from a given probability distribution

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)

tensor([[-1.1331, -0.6620, -0.6166,  0.0678],
        [-1.4232,  0.2294, -0.2682, -0.4998],
        [-1.1613,  0.5470, -0.6513, -1.2253]])

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).shape

torch.Size([3, 4])

# 2 Operations

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x +y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X.sum()

tensor(66.)

# 3 Broadcasting Mechanism
1. Matching Dimensions:  
Starting from the trailing (right-most) dimensions, the dimensions of the tensors are compared. Two dimensions are compatible if they are equal, or one of them is 1. Essentially, a dimension of size 1 can be stretched (replicated) to match the size of the other dimension.
2. Broadcasting Rules:
+ If the tensors have a different number of dimensions, the smaller tensor is padded with ones on its left side until both tensors have the same number of dimensions.
+ Once the tensors have the same number of dimensions, compare each dimension from right to left:
  + If the dimensions are equal, proceed to the next dimension.
  + If one of the dimensions is 1, it can be stretched to match the other dimension.
  + If the dimensions are neither equal nor 1, broadcasting is not possible and an error is raised.

In [22]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 4 Indexing and Slicing

In [24]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [25]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# 5 Saving Memory

Running operations can cause new memory to be allocated to host results.

In [27]:
before = id(Y)
Y = Y + X
id(Y) == before

False

performing in-place operations

In [28]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140259587262128
id(Z): 140259587262128


If the value of X is not reused in subsequent computations, we can also use X[:] = X + Y or X += Y to reduce the memory overhead of the operation.

In [29]:
before = id(X)
X += Y
id(X) == before

True

In [30]:
before = id(X)
X = X + Y
id(X) == before

False

In [31]:
before = id(X)
X[:] = X + Y
id(X) == before

True

# 6 Conversion to Other Python Objects

In [32]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [33]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 7 Tensor on GPU

In [34]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # Create Tensor on GPU
    x = x.to(device)                       # equals .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to() can also change the data type

tensor([2., 3., 5., 9.], device='cuda:0')
tensor([2., 3., 5., 9.], dtype=torch.float64)
