# What is NumPy?
+ NumPy is a Python library used for processing arrays.
+ It also has functions for working in the fields of linear algebra, Fourier transforms, and matrices.
+ NumPy was created by Travis Oliphant in 2005. It is an open-source project, and you can use it for free.
+ NumPy is short for Numerical Python.
# Why use NumPy?
+ In Python, we have lists that can serve the purpose of arrays, but they are slow to process.
+ NumPy provides an array object that is 50 times faster than traditional Python lists.
+ The array object in NumPy is called ndarray, and it offers many supporting functions that make operations on ndarray very easy.
+ Arrays are used very frequently in data science, where speed and resources are very important.
# Why is NumPy faster than lists?
+ Unlike lists, the arrays in NumPy are stored at one continuous place in memory, so processes can access and manipulate them very efficiently.
+ This behavior is called locality of reference in computer science.
+ This is the main reason why NumPy is faster than lists. Additionally, it is optimized to work with the latest CPU architectures.
# What language is NumPy written in?
NumPy is a Python library, and part of it is written in Python, but most of the parts that require fast computation are written in C or C++.
# Where is the NumPy code repository?
[source code](https://github.com/numpy/numpy)

# Check NumPy version
The version string is stored in the __version__ attribute.

In [1]:
import numpy as np
print(np.__version__)

1.23.5


# 1 Arrays
## Creating NumPy ndarray Object
We can create a NumPy ndarray object using the array() function.

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Array Dimensions 

In [4]:
arr1 = np.array(61) # 0-D
print(arr1)
arr2 = np.array([1, 2, 3, 4, 5, 6]) # 1-D
print(arr2)
arr3 = np.array([[1, 2, 3], 
                 [4, 5, 6]]) # 2-D
print(arr3)
arr4 = np.array([[[1, 2, 3], 
                 [4, 5, 6]], 
                [[1, 2, 3], 
                 [4, 5, 6]]]) # 3-D
print(arr4)

61
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Checking Dimensions: NumPy arrays have an attribute called ndim that returns an integer representing the number of dimensions (or ranks) of the array.

In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays  
An array can have any number of dimensions. When creating an array, you can define the number of dimensions by using the ndim argument.

In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


## Array Indexing
Accessing Array Elements

In [7]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


Accessing 2-D Arrays

In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('2nd element on 1st dim:', arr[0, 1])
print('5th element on 2nd dim:', arr[1, 4])

2nd element on 1st dim: 2
5th element on 2nd dim: 10


Accessing 3-D Arrays

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


Negative Indexing  
Use negative indexing to access an array from the end.

In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Last element from 2nd dim:', arr[1, -1])

Last element from 2nd dim: 10


## Array Slicing

Slicing Arrays  
In Python, slicing means taking elements from one given index to another given index. We pass slice instead of an index like this: [start:end]. We can also define the step, like this: [start:end:step].

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Slice elements from index 1 to index 4
print(arr[1:5])
# Slice elements from index 4 to the end
print(arr[4:])
# Slice elements from the start to index 4 (not included)
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


Negative Slicing  
Use the minus operator to refer to an index from the end.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Slice from the third last element to the second last element
print(arr[-3:-1])

[5 6]


Step

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Return every second element from index 1 to index 5
print(arr[1:5:2])
# Return every second element from the entire array
print(arr[::2])

[2 4]
[1 3 5 7]


Slicing 2-D Arrays

In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 2:3])
print(arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
[[3]
 [8]]
[[2 3 4]
 [7 8 9]]


# 2 Data Types
+ Data Types in Python
  By default, Python has the following data types:
  + strings - used to represent text data, enclosed in quotes. Example: "ABCD".
  + integer - used to represent integer numbers. Example: -1, -2, -3.
  + float - used to represent floating-point numbers. Example: 1.2, 42.42.
  + boolean - used to represent True or False.
  + complex - used to represent complex numbers. Example: 1.0 + 2.0j, 1.5 + 2.5j.
+ Data Types in NumPy
  NumPy has some additional data types, and it uses a character to represent them. For example, i for integer, u for unsigned integer, etc. Below is the list of all data types in NumPy and the characters used to represent them:
  + i - integer
  + b - boolean
  + u - unsigned integer
  + f - float
  + c - complex float
  + m - timedelta
  + M - datetime
  + O - object
  + S - string
  + U - unicode string
  + V - fixed chunk of memory for other types (void)

## Checking the Data Type of an Array
NumPy arrays have an attribute called dtype that returns the data type of the array:

In [18]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


< indicates the byte order (little-endian in this case).  
U indicates that the type is a Unicode string.  
6 indicates the number of characters in each string.

## What Happens if a Value Cannot be Converted?
If a value cannot be converted to the specified data type, NumPy will raise a ValueError:

In [19]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [68]:
arr = np.array(['1', '2', '3'], dtype='i')
print(arr)

[1 2 3]


## Converting Data Types on Existing Arrays
To change the data type of an existing array, use the astype() method. The astype() function creates a copy of the array and allows you to specify the data type as a parameter:

In [21]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
[ True False  True]
bool


# 3 NumPy Array Copy vs. View
The main difference between a copy and a view of an array is that a copy is a new array, while a view is just a view of the original array.  
+ Copy owns the data and any changes made to the copy will not affect the original array, and any changes made to the original array will not affect the copy.
+ View does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Copy

In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 61
print(arr)
print(x)

[1 2 3 4 5]
[61  2  3  4  5]


View

In [24]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 61
print(arr)
print(x)

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[61  2  3  4  5]
[61  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]


## Checking if an Array Owns its Data
Every NumPy array has an attribute called base. If the array owns its data, the base attribute will be None. Otherwise, the base attribute will reference the original object.

In [25]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
print(arr.base)

None
[1 2 3 4 5]
None


# 4 Shape
The shape of an array is the number of elements in each dimension.

## Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [26]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array:', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


## Reshaping Arrays

Reshape from 1-D to 2-D

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(arr.shape)
print(newarr)
print(newarr.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


Reshape from 1-D to 3-D

In [28]:
newarr = arr.reshape(2, 3, 2)

print(newarr)
print(newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


Can We Reshape into Any Shape?  
Yes, as long as the elements required for reshaping are equal in both shapes. We can reshape 8 elements 1D array into 2 rows and 4 columns 2D array, but we cannot reshape it into 3 rows and 2 columns 2D array because 8 elements cannot be evenly divided into 3 rows and 2 columns.

Does it Return a Copy or a View?

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
# The above output shows the original array, hence it is a view

[1 2 3 4 5 6 7 8]


Unknown Dimension  
Pass -1 as the dimension and NumPy will calculate this dimension for you.

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening the Arrays  
Flattening an array means converting a multidimensional array into a 1D array. We can use reshape(-1) to do this.

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# 5 Operation

## 5.1 NumPy Array Iteration

1-D

In [33]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


2-D

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)
# If we iterate on a n-D array, it will go through the first axis

for x in arr:
    for y in x:
        print(y)
# To return the actual values, the scalars, we need to iterate the arrays in each dimension

[1 2 3]
[4 5 6]
1
2
3
4
5
6


3-D

In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### nditer
In basic for loops, iterating through each scalar element of an array, we need to use n for loops for n-D arrays, which can be cumbersome for higher dimensional arrays.

In [36]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Iterating Arrays with Different Data Types

In [39]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


### Enumerated Iteration Using ndenumerate()

In [40]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

arr = np.array([[1, 2, 3], [4, 5, 6]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## 5.2 NumPy Array Concatenation
### Concatenating NumPy Arrays

In [43]:
arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])

arr = np.concatenate((arr1, arr2))
print(arr, arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


In [44]:
# Passing axis argument to concatenate 2-D arrays along axis 1
# When axis=1, the operation is performed along the second axis, which corresponds to columns in a 2D array.
arr = np.concatenate((arr1, arr2), axis=1)
print(arr, arr.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


### Stacking Arrays Using Stack Functions
Stacking is similar to concatenation, the only difference is that stacking is done along a new axis.

In [45]:
arr = np.stack((arr1, arr2), axis=0)
print(arr, arr.shape)

arr = np.stack((arr1, arr2), axis=1)
print(arr, arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] (2, 2, 2)


### Horizontal Stacking
NumPy provides a helper function: hstack() to stack along rows.

In [46]:
arr = np.hstack((arr1, arr2))
print(arr, arr.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


### Vertical Stacking
NumPy provides a helper function: vstack() to stack along columns.

In [47]:
arr = np.vstack((arr1, arr2))
print(arr, arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


### Depth Stacking
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [48]:
arr = np.dstack((arr1, arr2))
print(arr, arr.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] (2, 2, 2)


## 5.3 NumPy Array Splitting
### Splitting NumPy Arrays
Splitting is the opposite of concatenation.

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
# This returns a list containing three sub-arrays

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


### Using array_split and split
The array_split function allows splitting an array into an arbitrary number of sub-arrays, whereas split requires that the number of splits must evenly divide the array.

In [50]:
newarr = np.array_split(arr, 4)
print(newarr)

newarr = np.split(arr, 3)
print(newarr)

newarr = np.split(arr, 4)
print(newarr)
# This will raise a ValueError because the array cannot be evenly split into 4 parts.

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


ValueError: array split does not result in an equal division

### Splitting 2-D Arrays
When splitting 2-D arrays, the same logic applies. Use array_split() method, passing the array to be split and the number of splits required.

In [51]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.shape)

newarr = np.array_split(arr, 3)
print(newarr)

arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])
print(arr.shape)

newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 3, axis=1)
print(newarr)

(3, 4)
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
(3, 6)
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]])]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]


### Using hsplit
Another way to split arrays is using the hsplit() function, which is the opposite of hstack().

In [52]:
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]


## 5.4 NumPy Array Search
### Searching Arrays
You can search for specific values in an array and return the indices of the matching elements. To search an array, use the where() method.

In [53]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


The value 4 is found at indices 3, 5, and 6

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [55]:
x = np.where(arr % 2 == 1)
print(x)

(array([0, 2, 4, 6]),)


### Searching Sorted Arrays
left: a[i-1] < v <= a[i]  
right: a[i-1] <= v < a[i]

In [56]:
arr = np.array([6, 8, 9, 15]) # This method starts searching from the left and returns the first index where the value 9 is not greater than the next value.
x = np.searchsorted(arr, 9)
print(x)

2


In [57]:
x = np.searchsorted(arr, 9, side='right') # This method starts searching from the right and returns the first index where the value 9 is not less than the next value.
print(x)

3


### Multiple Values
To search for multiple values, use an array with the specified values:

In [58]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


## 5.5 NumPy Array Sorting
### Sorting Arrays

In [59]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [60]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [61]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


### Sorting 2-D Arrays

In [62]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## 5.6 NumPy Array Filtering

### Filtering Arrays
Filtering arrays involves creating a Boolean array where some values are True and others are False, and then extracting the elements corresponding to the True values.

In [63]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


### Creating a Filter Array
Creating a filter array involves iterating over the elements in the original array and applying a condition to set True or False for each element.

In [64]:
arr = np.array([41, 42, 43, 44])
filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(newarr)

[43 44]


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []

for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(newarr)

[2 4 6]


### Directly Create Filters from Arrays

In [66]:
arr = np.array([61, 62, 63, 64, 65])
filter_arr = arr > 62
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True  True]
[63 64 65]


Creating filters based on conditions:

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
