In [1]:
import torch

# 1 Create Tensor

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x = torch.empty(5, 3) # creates a tensor without initializing its elements
x

tensor([[-1.7724e-38,  7.7352e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
x = torch.rand(5, 3) # create a randomly initialized tensor
x

tensor([[0.1945, 0.4846, 0.4627],
        [0.1619, 0.6300, 0.8410],
        [0.3579, 0.1142, 0.9451],
        [0.8352, 0.4999, 0.9804],
        [0.9957, 0.7526, 0.5363]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

## Attribute:

In [7]:
x = torch.arange(12)
x.shape

torch.Size([12])

In [8]:
x.size()

torch.Size([12])

torch.Size is a tuple

In [9]:
x.numel()

12

reshape a tensor but do not change the numel and values

In [10]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

all 0, all 1, other constants or sample each element randomly (and independently) from a given probability distribution

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)

tensor([[ 0.5673, -0.9995,  0.5289,  0.2715],
        [ 0.8978, -0.1406,  1.6074, -0.7789],
        [ 0.3968, -1.2423,  0.4045, -0.1519]])

In [14]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).shape

torch.Size([3, 4])

# 2 Operations

## 算术操作

In [16]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x +y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [17]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [24]:
y = torch.rand(5, 3)
x = torch.ones(5, 3)
result = torch.empty(5, 3)
torch.add(x, y, out=result) # 指定输出
print(result)

tensor([[1.7734, 1.9570, 1.5336],
        [1.1123, 1.2705, 1.7364],
        [1.6674, 1.3459, 1.0258],
        [1.1404, 1.4354, 1.5754],
        [1.9626, 1.3008, 1.3454]])


In [25]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.7734, 1.9570, 1.5336],
        [1.1123, 1.2705, 1.7364],
        [1.6674, 1.3459, 1.0258],
        [1.1404, 1.4354, 1.5754],
        [1.9626, 1.3008, 1.3454]])


## 索引
类似于Python中的索引，**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。**

In [26]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([2., 2., 2.])
tensor([2., 2., 2.])


## 改变形状

使用view()来改变tensor的形状

In [27]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [28]:
x += 1
print(x)
print(y) # 也加了1

tensor([[3., 3., 3.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([3., 3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


如果我们想返回一个真正不共享data内存的副本，Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。

推荐先用clone创造一个副本然后再使用view。

In [29]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[2., 2., 2.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([3., 3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


> 使用`clone`还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源`Tensor`。

In [30]:
# 创建一个需要梯度的张量
x = torch.tensor([2.0, 3.0], requires_grad=True)

# 克隆一个新的张量
y = x.clone()

# 对克隆出来的张量进行操作
z = y**2

# 进行反向传播，计算梯度
z.sum().backward()

# 输出原始张量和克隆张量的梯度
print(x.grad)  # 期望输出 [4.0, 6.0]
print(y.grad)  # 由于y是克隆出来的，它本身不需要梯度，所以它的grad是None

tensor([4., 6.])
None


C:\Users\shayg\AppData\Local\Temp\ipykernel_29428\2724706976.py:15: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print(y.grad)  # 由于y是克隆出来的，它本身不需要梯度，所以它的grad是None


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1816])
-0.18159054219722748


## Concatenate：沿着某个维度将多个张量拼接在一起
+ 沿着行拼接（维度0，即竖着拼接）：要求列数相同，是`增加行数`的操作
+ 沿着列拼接（维度1，即横着拼接）：要求行数相同，是`增加列数`的操作

In [32]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [33]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [34]:
X.sum()

tensor(66.)

# 3 Broadcasting Mechanism
1. Matching Dimensions:  
Starting from the trailing (right-most) dimensions, the dimensions of the tensors are compared. Two dimensions are compatible if they are equal, or one of them is 1. Essentially, a dimension of size 1 can be stretched (replicated) to match the size of the other dimension.
2. Broadcasting Rules:
+ If the tensors have a different number of dimensions, the smaller tensor is padded with ones on its left side until both tensors have the same number of dimensions.
+ Once the tensors have the same number of dimensions, compare each dimension from right to left:
  + If the dimensions are equal, proceed to the next dimension.
  + If one of the dimensions is 1, it can be stretched to match the other dimension.
  + If the dimensions are neither equal nor 1, broadcasting is not possible and an error is raised.

In [22]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 4 Saving Memory

In [35]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False，y指向新开辟的内存

False


In [36]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True，y指向原来的内存

True


> 注：虽然`view`返回的`Tensor`与源`Tensor`是共享`data`的，但是依然是一个新的`Tensor`（因为`Tensor`除了包含`data`外还有一些其他属性），二者id（内存地址）并不一致。

# 5 Conversion to Other Python Objects (Numpy)

我们很容易用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。但是需要注意的一点是：**这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**

## Tensor -> Numpy: `numpy()`

In [37]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


## Numpy -> Tensor: `from_numpy()`

In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


#### 还有一个常用的将NumPy中的array转换成Tensor的方法就是torch.tensor(), 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的Tensor和原来的数据不再共享内存。

In [39]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [40]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 6 Tensor on GPU

In [41]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # Create Tensor on GPU
    x = x.to(device)                       # equals .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to() can also change the data type

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
