## Create an artificial dataset and save it in a CSV (comma-separated values) file.

In [2]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # column name
    f.write('NA,Pave,127500\n') # every line represents a data sample
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [7]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] # index location
inputs = inputs.fillna(inputs.mean())
print(inputs)

TypeError: can only concatenate str (not "int") to str

In [11]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [12]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] # index location
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [13]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [18]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [21]:
import torch
inputs = inputs.astype(int)
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3, 1, 0],
         [2, 0, 1],
         [4, 0, 1],
         [3, 0, 1]]),
 tensor([127500, 106000, 178100, 140000]))

In [20]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))